### PR TITLE
Give a more elaborate example of using `render_dynamic_template_component` on the README

### PR DESCRIPTION
**Pull request by amos-kibet**

### CODE REVIEW

**Comment by akoutmos** [comment]
Thanks for the contribution!

**Comment by amos-kibet** [comment]
Hey @akoutmos, 
Big thanks for creating this awesome lib. Not sure if I should be asking here, but  is it possible to use the `.heex` extension instead of the `.eex` for templates?

**Comment by akoutmos** [comment]
That is on my todo list as I would like to have the mjml templates automatically formatted and also have their structure verified. Not sure on what the timeline is for that work though.

**Comment by amos-kibet** [comment]
My concern was actually on formatting.
No worries, take your time; I'll be on the lookout for updates.

**Pull request merged**
